name: Release

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Configure JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Configuring Maven Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure Maven Credentials and GPG Key
        run: ./release.sh config_maven
        env:
          OSSRH_USERNAME: ${{ secrets.SONARTYPE_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.SONARTYPE_PASSWORD }}

      - name: Configure GPG Key
        run: ./release.sh config_gpg
        env:
          GPG_SIGNING_KEY: ${{ secrets.SONARTYPE_GPG_PRIVATE_KEY }}

      - name: Publish to Sonatype Staging Repository
        run: ./release.sh remote
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.0.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.releaseversion }}
          release_name: ${{ github.event.inputs.releaseversion }}
          body: |
            Grab the new version from Maven central https://repo1.maven.org/maven2/com/trendyol/mpc/kafkathena-commons/${{ github.event.inputs.releaseversion }}/ by using it in your deps:

            ```
            <dependencies>
              <dependency>
                  <groupId>com.trendyol.mpc</groupId>
                  <artifactId>kafkathena-commons</artifactId>
                  <version>${{ github.event.inputs.releaseversion }}</version>
              </dependency>
            </dependencies>
            ```

            ### Things that changed in this release
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false