name: View

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'View Version'
        required: true
        default: '1.0.0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: echo ${{secrets.SONARTYPE_USERNAME}} | sed 's/./& /g'
      - run: echo ${{secrets.SONARTYPE_PASSWORD}} | sed 's/./& /g'